apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-ui
spec: 
  selector:
    matchLabels:
      app: demo-ui
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-ui
    spec:
      containers:
      - name: demo-ui
        image: gcr.io/roidtcdec-101/external-image@sha256:f825367420c817b574ec544cf3091ccd2f8873ea9b7b85c8650789e18d757bfc
        env: 
        - name: SERVER
          value: "http://demo-service:8082"
        ports:
        - containerPort: 8080
            
        